sudo: required
dist: trusty
language: cpp
compiler: gcc

branches:
  only:
    - travis

before_install: 
  - sudo apt-get -qq update
  - sudo apt install freeglut3-dev

install:
  - echo "Hey 3!"

script:
  - mkdir build && cd build
  - cmake ..
  - make